### ISSUE TITLE
Trouver une solution de responsitivité

### ISSUE THREAD

**Issue by RebsonDodjiDahouede** [RolandRKT/SAE-3.05#17]
Mettre en place la responsivité des pages implémentées

**Comment by RolandRKT** [comment]
Nous avons décidés avec Maverick d'adapter le site selon si l'utilisateur est sur pc ou mobile. Nous avons donc rendu responsive la page home, puis créer une version mobile pour la page inscription et login.

**Comment by MaverickPrevost** [comment]
Responsivité effectuée.
