### ISSUE TITLE
Établir les diagrammes nécessaires

### ISSUE THREAD

**Issue by RolandRKT** [RolandRKT/SAE-3.05#32]
Faire les CU textuelles et diagramme d'activité pour :

- Inscription à un parcours
- Inscription en tant que client
- Création d'un parcours
- Suivre un parcours en tant que client

**Comment by ThibaultSL72** [comment]
Actuellement CU textuelles pour: 
    - connexion
    - inscription en tant que client
    - inscription à un parcours     
FAIT

Diagramme d'activité englobant connexion, inscription en tant que client et inscription à un parcours: FAIT

**Comment by ThibaultSL72** [comment]
Fin
CU textuelle création parcours et son diagramme d'activité: FAIT

**Comment by ThibaultSL72** [comment]
Fin
CU textuelle création parcours et son diagramme d'activité: FAIT
