### ISSUE TITLE
[Feature] : creation de CU

### ISSUE THREAD

**Issue by ahmet40** [RolandRKT/SAE-3.05#34]
cette issu permettera de cree deux CU. le premier sera pour la enlever l'inscription d'un utilisateur à un parcours depuis l'admin. et le second sera pour la suppression d'un parcours.

**Comment by ThibaultSL72** [comment]
FIN:
- suppression d'un parcours
- suppression d'un client à un parcours
FAIT CU textuelle et diagramme d'activité

**Comment by ThibaultSL72** [comment]
FIN:
- suppression d'un parcours
- suppression d'un client à un parcours
- FAIT CU textuelle et diagramme d'activité
